### ISSUE TITLE
Add license statement

### ISSUE THREAD

**Issue by seiferma** [eclipseguru/missing-swt-fragments#1]
First of all, thanks for providing [this workaround](https://bugs.eclipse.org/bugs/show_bug.cgi?id=491951#c35) until the Neon repository is fixed.

In order to make using this workaround legal, could you please provide a license statement (e.g. EPL) in your repository or even better in your features?

**Comment by guw** [comment]
This is all EPL (inherited from of SWT). Can you submit a pull request with the changes you'd like to see? This is build-time only.

**Comment by guw** [comment]
@seiferma Sorry for the long delay. I missed/did not get a notification for the issue.

**Comment by seiferma** [comment]
Hi @guw 

that is no problem. I added a pull request.
